# Generated by Django 2.2.7 on 2019-11-15 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 37, 52, 349882))),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=40)),
                ('n_wheels', models.IntegerField(default=2)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_maker', models.CharField(max_length=70)),
                ('vehicle_model', models.CharField(max_length=70)),
                ('n_passengers_dead', models.IntegerField()),
                ('n_passengers_injured', models.IntegerField()),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acciTracker.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Crowd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 12, 37, 52, 350201))),
                ('count', models.IntegerField(blank=True, default=0)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acciTracker.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people_involved', models.IntegerField(default=0)),
                ('n_children_involved', models.IntegerField(default=0)),
                ('n_injured', models.IntegerField(default=0)),
                ('n_dead', models.IntegerField(default=0)),
                ('mistake', models.CharField(default='Not Determined', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=700)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acciTracker.Accident')),
            ],
        ),
    ]
