# Generated by Django 2.2.7 on 2019-11-15 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciTracker', '0002_auto_20191115_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accident',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 4, 40, 107783)),
        ),
        migrations.AlterField(
            model_name='crowd',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 4, 40, 108104)),
        ),
    ]
